import { Check, ChevronRight, CircleDot, RefreshCw, Search, ShieldCheck, Sparkles } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"

const steps = [
  { label: "Initial Detection", status: "MISSED", time: "14:31:42 UTC", icon: Search, tone: "border-red-500/60 bg-red-500/10 text-red-300", detail: "Behavioral mimicry scenario passed through the initial policy set." },
  { label: "Feedback Analysis", status: "UPDATING", time: "14:32:01 UTC", icon: Sparkles, tone: "border-yellow-500/60 bg-yellow-500/10 text-yellow-300", detail: "The defense loop is converting the miss into three new protections." },
    { label: "Feedback Analysis", status: "UPDATING", time: "14:32:01 UTC", icon: Sparkles, tone: "border-yellow-500/60 bg-yellow-500/10 text-yellow-300", detail: "The defense loop is converting the miss into three new protections." },
  { label: "Retest", status: "QUEUED", time: "14:32:08 UTC", icon: RefreshCw, tone: "border-slate-600 bg-slate-800/50 text-slate-300", detail: "The same attack will be replayed against the updated ensemble." },
  { label: "Final Detection", status: "PENDING", time: "--:--:-- UTC", icon: ShieldCheck, tone: "border-slate-700 bg-slate-800/30 text-slate-500", detail: "Waiting for the retest result to close the feedback loop." },
]

export function AdaptiveDefense() {
  return <div className="space-y-8"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-emerald-400">Continuous learning / 02</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-white">Adaptive Defense</h2><p className="mt-2 max-w-2xl text-sm text-slate-500">Watch the autonomous feedback loop turn missed signals into stronger detection coverage.</p></div><Card className="border-slate-800 bg-[#0d1520] shadow-none"><CardContent className="p-5 sm:p-8"><div className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-6"><div><p className="font-mono text-[10px] uppercase tracking-wider text-slate-600">Active learning case</p><p className="mt-2 font-mono text-lg text-slate-200">CASE-2026-0825-0190</p></div><Badge variant="outline" className="border-blue-500/30 bg-blue-500/10 font-mono text-[10px] text-blue-300">LOOP IN PROGRESS</Badge></div><div className="relative space-y-8">{steps.map(({ label, status, time, icon: Icon, tone, detail }, index) => <div key={label} className="relative flex gap-5 sm:gap-7">{index < steps.length - 1 && <div className="absolute left-5 top-12 h-[calc(100%+2rem)] w-px bg-slate-800" />}{index > 0 && <ChevronRight className="absolute -left-1 top-0 hidden size-4 -rotate-90 text-slate-700 sm:block" />}<div className={`relative z-1 flex size-10 shrink-0 items-center justify-center rounded-full border ${tone}`}><Icon className="size-4" /></div><div className="min-w-0 flex-1 pb-1"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><h3 className="font-medium text-slate-200">{label}</h3><span className="font-mono text-[10px] text-slate-600">{time}</span><Badge variant="outline" className={`font-mono text-[9px] ${status === "MISSED" ? "border-red-500/30 text-red-300" : status === "UPDATING" ? "border-blue-500/30 text-blue-300" : "border-slate-700 text-slate-500"}`}>{status}</Badge></div><p className="mt-2 text-sm leading-relaxed text-slate-500">{detail}</p>{index === 1 && <div className="mt-4 grid gap-2 sm:grid-cols-3"><span className="flex items-center gap-2 border border-blue-500/20 bg-blue-500/5 px-3 py-2 font-mono text-[10px] text-blue-200"><Check className="size-3 text-blue-400" />Fraud Pattern Knowledge</span><span className="flex items-center gap-2 border border-blue-500/20 bg-blue-500/5 px-3 py-2 font-mono text-[10px] text-blue-200"><Check className="size-3 text-blue-400" />Detection Rule</span><span className="flex items-center gap-2 border border-blue-500/20 bg-blue-500/5 px-3 py-2 font-mono text-[10px] text-blue-200"><Check className="size-3 text-blue-400" />Attack Signature</span></div>}</div></div>)}</div></CardContent></Card><div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-wider text-slate-600"><CircleDot className="size-3 text-emerald-400" />Last model sync 14:28 UTC <Separator orientation="vertical" className="h-3 bg-slate-800" /> Next evaluation in 42 sec</div></div>
}